[KOGITO-8544] Add products sample dashboard
kiegroup/kie-samples pull request #2
Opened 2023-01-30 09:56 UTC by kumaradityaraj

2023-01-31 14:19 UTC, adrielparedes commented
@kumaradityaraj `products-dashboard` folder should go inside `samples` folder.

2023-01-31 14:20 UTC, adrielparedes requested changes

2023-01-31 14:20 UTC, adrielparedes commented on products-dashboard/definition.json
> +{
Also, please check this file because it contains default information. Change them with data related to the project you are creating

2023-01-31 14:45 UTC, jesuino requested changes
Hello @kumaradityaraj 

Thanks for your contribution!

I am suggesting some changes, would you please apply these changes and update this PR? Just modify as suggested, add and commit to your branch and push your changes

I also noticed that the SVG `products-dashboard/products-dashboard.svg` is empty, would you please:

1) Take a screenshot of the dashboards
2) Convert it to SVG - there are several ways of doing this - one way I like is opening the PNG file in Inkscape, a free tool, and saving it as plain SVG


Thanks!

2023-01-31 14:45 UTC, jesuino commented on products-dashboard/definition.json
> +    "resources": [
you can leave resources as an empty array:

"resources": []

2023-01-31 14:45 UTC, jesuino commented on products-dashboard/definition.json
> +    "authors": [
Fill this with your information

2023-01-31 14:45 UTC, jesuino commented on products-dashboard/products-dashboard.dash.yaml
> +          type: TABLE
You can remove this line, the type is not required for tables - it is the default type

2023-01-31 14:45 UTC, jesuino commented on products-dashboard/products-dashboard.dash.yaml
> +global:
Please format this file in kubersmarts or in VSCode:

* Open the code 
* Hold: `Ctrl + Shift` and press `i`
It should correctly indent this file

2023-02-01 18:43 UTC, jesuino commented
Hello @kumaradityaraj 

The SVG is looking good but notice that the dashboard is in dark mode, for some reason it the screenshot shows it in light mode!

2023-02-01 19:07 UTC, adrielparedes requested changes

2023-02-01 19:07 UTC, adrielparedes commented on samples/products-dashboard/definition.json
> +  "description": "Products Dashboard",
Maybe we can add a little bit more information here. Remember this part is going to be shown as the first description on  our webs

2023-02-01 19:08 UTC, adrielparedes commented
Eveything so far is looking good, just some minor adjustements, well done @kumaradityaraj !

2023-02-02 13:51 UTC, adrielparedes approved these changes

2023-02-02 14:49 UTC, jesuino approved these changes
LGTM, thanks!

2023-02-02 14:53 UTC, merged